//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by X-FLR6.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDC_DELETEPT                    101
#define IDD_MINVCTRLBAR                 103
#define IDC_INSERT                      104
#define IDC_RESET                       105
#define IDC_DELETEALL                   106
#define IDC_INSERTPT                    107
#define IDC_DELETE                      108
#define IDC_RENAME                      109
#define IDC_SELECT                      110
#define IDR_XFLR5BAR                    111
#define IDM_MIAREX_MENU                 112
#define IDR_MAINFRAME                   128
#define IDS_WINGSPAN                    129
#define IDS_ALPHA                       130
#define IDS_WINGAREA                    131
#define IDS_PLANEWEIGHT                 132
#define IDS_WINGLOAD                    133
#define IDS_TAILVOLUME                  134
#define IDS_ROOTCHORD                   135
#define IDS_MAC                         136
#define IDS_TWISTTIP                    137
#define IDS_AR                          138
#define IDD_LINEPICKERDLG               139
#define IDS_RTTIPSWEEP                  140
#define IDD_PREFERENCES                 141
#define IDS_LIFTCOEF                    142
#define IDS_DRAGCOEF                    143
#define IDD_CADDDLG                     144
#define IDS_INDUCEDMOMENT               145
#define IDS_THICKNESS                   146
#define IDS_MAXTHICKNESSPOS             147
#define IDD_GRAPHOPTIONS                148
#define IDS_MAXCAMBERPOS                149
#define IDD_2DPANELDLG                  150
#define IDS_LOWERTRANS                  151
#define IDS_TEHINGEMOMENT               152
#define IDD_FOILCLRDLG                  153
#define IDD_GRAPHDLG                    154
#define IDD_GEOMDLG                     155
#define IDD_INTERDLG                    156
#define IDD_BATCHANALYSISDLG            157
#define IDD_DISPLAYBAR                  158
#define IDD_WINGDLG                     160
#define IDM_AFOIL_MENU                  161
#define IDD_WPOLARANALYSIS              162
#define IDD_TOOLBARDLG                  163
#define IDD_AGRIDDLG                    164
#define IDR_AFOILBAR                    165
#define IDS_MAXCAMBER                   166
#define IDD_NAMEDLG                     167
#define IDS_UPPERTRANS                  168
#define IDS_ROLLINGMOMENT               169
#define IDD_ADVDLG                      170
#define IDD_FINVCTRLBAR                 173
#define IDD_PERTDLG                     174
#define IDR_XINVERSEBAR                 177
#define IDD_INVCOLORDLG                 179
#define IDD_SELECTFOILDLG               185
#define IDR_CTXDESIGNMENU               187
#define IDR_CTXWNGMENU                  188
#define IDR_CTXMAINMENU                 193
#define IDM_XDIRECT_MENU                195
#define IDS_TR                          196
#define IDD_CLRDLG                      197
#define IDS_POINTOUT                    198
#define IDD_VISCDLG                     199
#define IDD_FOILANALYSISDLG             204
#define IDD_UNITSDLG                    212
#define IDC_HANDCURSOR                  214
#define IDC_HMOVE                       215
#define IDD_USERVARDLG                  219
#define IDR_CTXXDIRECTPLRMENU           220
#define IDR_CTXWINGPLRMENU              221
#define IDD_EDITPLRDLG                  222
#define IDR_CTXXDIRECTFOILMENU          223
#define IDD_GRIDDLG                     224
#define IDD_FONTDLG                     225
#define IDD_SCALEDLG                    226
#define IDD_BACKDLG                     235
#define IDR_CTXINVMENU                  236
#define IDD_WGRAPHVARDLG                237
#define IDD_WADVDLG                     239
#define IDD_PLANEDLG                    249
#define IDR_CTXWINGOPPMENU              250
#define IDM_XINVERSE_MENU               251
#define IDR_MIAREXBAR                   252
#define IDD_WINGSCALEDLG                256
#define IDR_CTXINVFOIL                  257
#define IDD_POLARFILTER                 258
#define IDR_CTXWING3DMENU               259
#define IDD_POLARBAR                    261
#define IDD_OPERDLGBAR                  262
#define IDD_AFOILCTRLBAR                263
#define IDR_DOCUMENT                    265
#define IDD_PRINTOPTIONSDLG             269
#define IDD_TEGAPDLG                    273
#define IDD_FLAPDLG                     283
#define IDD_NACADLG                     293
#define IDD_SAVEOPTIONSDLG              310
#define IDD_IMPORTWINGDLG               311
#define IDD_SCALEOPPBAR                 312
#define IDD_CPSCALEDLG                  314
#define IDD_3DPANELDLG                  315
#define IDS_LEHINGEMOMENT               316
#define IDD_BODYNURBSDLG                317
#define IDC_MAXWAKEITER                 320
#define IDD_MODDLG                      325
#define IDD_FLOWLINESDLG                327
#define IDD_MESSAGEDLG                  328
#define IDD_GLLIGHT                     329
#define IDD_SPLINECONTROLSDLG           331
#define IDD_LECIRCLEDLG                 332
#define IDR_CTXAFOILCTRLMENU            333
#define IDD_UFOLISTDLG                  334
#define IDS_AIRFOILYAWING               341
#define IDS_FLAPMOMENT                  342
#define IDS_TOTALPANELS                 343
#define IDS_FLAPANGLE                   344
#define IDS_XHINGE                      345
#define IDS_YHINGE                      346
#define IDS_POLARTYPE                   347
#define IDS_FOILNORMALIZATION           348
#define IDS_FORCEDUPPERTRANS            349
#define IDD_SPANPOSBAR                  350
#define IDD_WAKEPARAMSDLG               352
#define IDS_FORCEDLOWERTRANS            353
#define IDR_CTXBODYFRAMECTRLMENU        354
#define IDR_CTXBODYPOINTCTRLMENU        355
#define IDR_CTXBODYCTRLMENU             356
#define IDD_VIEWBITMAP                  362
#define IDC_SHOWPRESSURE                1001
#define IDC_REMAX                       1003
#define IDC_REYNOLDS                    1004
#define IDC_MACH                        1005
#define IDC_NCRIT                       1006
#define IDC_SEQUENCE                    1007
#define IDC_REINC                       1010
#define IDC_TAPERRATIO                  1011
#define IDC_ANALYZE                     1012
#define IDC_ALPHA                       1013
#define IDC_MEANCHORD                   1014
#define IDC_BETA                        1015
#define IDC_AEROCHORD                   1016
#define IDC_YMAC                        1017
#define IDC_DALPHA                      1018
#define IDC_VLMPANELS                   1019
#define IDC_NEWNAME                     1020
#define IDC_WPOLARNAME                  1021
#define IDC_WSEQUENCE                   1023
#define IDC_MIAREXWINGBAR               1024
#define IDC_PARAM1                      1025
#define IDC_PARAM2                      1026
#define IDC_PARAM3                      1027
#define IDC_RETIP                       1029
#define IDC_ACTRLBAR                    1030
#define IDC_DALPHASTAT                  1031
#define IDC_MINVCTRLBAR                 1032
#define IDC_YMAINGRID                   1034
#define IDC_XGRIDSTYLE                  1036
#define IDC_RELAX                       1037
#define IDC_GRIDSTYLE2                  1037
#define IDC_YGRIDSTYLE                  1038
#define IDC_VORTEXPOS                   1038
#define IDC_ITERMAX                     1039
#define IDC_TOTALWAKELENGTH             1040
#define IDC_ALPHAPREC                   1041
#define IDC_LEGENDFONT                  1042
#define IDC_WAKEPANELFACTOR             1042
#define IDC_NSTAT                       1043
#define IDC_UNIFORM                     1044
#define IDC_MINPANELSIZE                1044
#define IDC_INTERNODES                  1045
#define IDC_CTRLPOS                     1046
#define IDC_TO                          1048
#define IDC_CTRRAT                      1054
#define IDC_XSREF1                      1055
#define IDC_ANIMATE                     1056
#define IDC_SLINK                       1057
#define IDC_ACL1                        1058
#define IDC_ACL2                        1059
#define IDC_MMAX                        1060
#define IDC_LORIGIN                     1061
#define IDC_DMIN                        1062
#define IDC_DMAX                        1063
#define IDC_DORIGIN                     1064
#define IDC_DUNIT                       1065
#define IDC_AUTOGRAPH                   1066
#define IDC_AMIN                        1067
#define IDC_AMAX                        1068
#define IDC_AORIGIN                     1069
#define IDC_AUNIT                       1071
#define IDC_PRESSURE                    1072
#define IDC_MMIN                        1073
#define IDC_NEUTRALSTYLE                1074
#define IDC_MORIGIN                     1076
#define IDC_MUNIT                       1077
#define IDC_THICKNESS                   1080
#define IDC_VISIBLE                     1081
#define IDC_XTHICKNESS                  1082
#define IDC_CENTERLINE                  1083
#define IDC_MODELPOINTS                 1084
#define IDC_LERAD                       1091
#define IDC_OUTEXTRADOS                 1092
#define IDC_OUTINTRADOS                 1093
#define IDC_DEGEXTRADOS                 1096
#define IDC_DEGINTRADOS                 1097
#define IDC_TITLEFONT                   1098
#define IDC_GRAPHCLR                    1099
#define IDC_STYLE                       1100
#define IDC_WIDTH                       1101
#define IDC_COLORBTN                    1102
#define IDC_WINGCOLOR                   1103
#define IDC_VDRAG                       1104
#define IDC_TOPTRANS                    1105
#define IDC_BOTTRANS                    1106
#define IDC_STREAM                      1107
#define IDC_3DVORTICES                  1108
#define IDC_XCP                         1109
#define IDC_IDRAG                       1110
#define IDC_DOWNWASH                    1111
#define IDC_WAKE                        1112
#define IDC_MOMENTS                     1113
#define IDC_CL                          1114
#define IDC_XMIN                        1115
#define IDC_WNDTXTFONT                  1116
#define IDC_XMAX                        1119
#define IDC_XO                          1120
#define IDC_XUNIT                       1121
#define IDC_APPLYSPLINE                 1126
#define IDC_AXISSTYLE                   1128
#define IDC_SMOOTH                      1129
#define IDC_XMAINSTYLE                  1130
#define IDC_PERT                        1131
#define IDC_YMAINSTYLE                  1132
#define IDC_TEFLAPCHECK                 1133
#define IDC_LEFLAPCHECK                 1134
#define IDC_YMINCHECK                   1135
#define IDC_TEXHINGE                    1136
#define IDC_YMINSTYLE                   1137
#define IDC_LEXHINGE                    1137
#define IDC_RETYP                       1138
#define IDC_MATYP                       1139
#define IDC_SPECTYP                     1140
#define IDC_INITBL                      1141
#define IDC_SHOWTEXTOUTPUT              1142
#define IDC_STOREOPP                    1143
#define IDC_XSEL                        1144
#define IDC_YSEL                        1145
#define IDC_ADDED                       1146
#define IDC_VACCEL                      1147
#define IDC_INVITER                     1149
#define IDC_MAXANGLE                    1150
#define IDC_ITERLIM                     1152
#define IDC_TOTAL                       1153
#define IDC_ATPANEL                     1154
#define IDC_SPININ                      1155
#define IDC_SPINOUT                     1156
#define IDC_YMIN                        1160
#define IDC_YMAX                        1161
#define IDC_YO                          1162
#define IDC_YUNIT                       1163
#define IDC_XMAJSTYLE                   1167
#define IDC_YMAJSTYLE                   1168
#define IDC_LERADCHECK                  1169
#define IDC_BORDERSTYLE                 1170
#define IDC_SHOWSPLINE                  1171
#define IDC_TGAPDX                      1172
#define IDC_TANGLE                      1173
#define IDC_SYMM                        1175
#define IDC_TGAPDY                      1176
#define IDC_NEWSPLINE                   1177
#define IDC_MARK                        1178
#define IDC_SPEC                        1179
#define IDC_QUESTION                    1180
#define IDC_OUTPUT                      1182
#define IDC_FOILCOLOR                   1184
#define IDC_NEWPLRNAME                  1185
#define IDC_SHOWPOINTS                  1187
#define IDC_CAMBER                      1195
#define IDC_FOIL1                       1196
#define IDC_XCAMBER                     1197
#define IDC_WNDCLR                      1198
#define IDC_FOIL2                       1200
#define IDC_THICKNESS1                  1201
#define IDC_CAMBER1                     1202
#define IDC_CAMBER2                     1203
#define IDC_THICKNESS2                  1204
#define IDC_MIXT                        1205
#define IDC_CAMBER0                     1206
#define IDC_FRAC                        1207
#define IDC_THICKNESS0                  1208
#define IDC_OUTTEXT                     1209
#define IDC_AUTOX                       1210
#define IDC_AUTOY                       1211
#define IDC_YINVERTED                   1212
#define IDC_REMIN                       1213
#define IDC_SPMIN                       1214
#define IDC_CLOSE                       1215
#define IDC_SKIPPOINT                   1217
#define IDC_SKIPPOLAR                   1218
#define IDC_CAMBERSLIDE                 1219
#define IDC_THICKSLIDE                  1220
#define IDC_CAMB                        1221
#define IDC_FOIL                        1222
#define IDC_XCAMBERSLIDE                1225
#define IDC_XTHICKSLIDE                 1226
#define IDC_BL                          1227
#define IDC_SPINC                       1228
#define IDC_WEIGHT                      1246
#define IDC_DOWNWASHSCALE               1247
#define IDC_DRAGSCALE                   1248
#define IDC_VOLUME                      1249
#define IDC_UNIFORM2                    1250
#define IDC_WANALYSIS                   1257
#define IDC_SPAN                        1258
#define IDC_SHOWBL                      1259
#define IDC_SPANXY                      1259
#define IDC_ALPHAMAX                    1260
#define IDC_DELTAALPHA                  1261
#define IDC_QINF                        1262
#define IDC_XTRIP1                      1263
#define IDC_XTRIP2                      1264
#define IDC_XCMREF                      1265
#define IDC_ALPHASTAT                   1266
#define IDC_ASPECTRATIO                 1267
#define IDC_SPMAX                       1268
#define IDC_LIFTSCALE                   1269
#define IDC_SRE                         1270
#define IDC_WINGLOAD                    1271
#define IDC_RRE                         1272
#define IDC_SURFACE                     1273
#define IDC_QINFCL                      1274
#define IDC_SURFACEXY                   1274
#define IDC_VISCOUS                     1275
#define IDC_WINGNAME                    1276
#define IDC_THINSURFACES                1277
#define IDC_SYMETRIC                    1278
#define IDC_FROM                        1280
#define IDC_ANGTOL                      1281
#define IDC_NPANELS                     1283
#define IDC_NXPANELS                    1284
#define IDC_CVPAR                       1285
#define IDC_CTERAT                      1288
#define IDC_XPREF1                      1291
#define IDC_LEYHINGE                    1292
#define IDC_SPEED                       1294
#define IDC_XSREF2                      1295
#define IDC_REFLECTEDSTYLE              1296
#define IDC_LEFLAPANGLE                 1297
#define IDC_XPREF2                      1298
#define IDC_NAME1                       1299
#define IDC_NAME2                       1300
#define IDC_LMAX                        1301
#define IDC_LMIN                        1302
#define IDC_LUNIT                       1303
#define IDC_LUNIT2                      1305
#define IDC_XMAJCHECK                   1306
#define IDC_YMAJCHECK                   1307
#define IDC_TEFLAPANGLE                 1308
#define IDC_XMINCHECK                   1309
#define IDC_TEYHINGE                    1310
#define IDC_XMINSTYLE                   1311
#define IDC_ANALYSIS                    1312
#define IDC_MINSTYLE2                   1313
#define IDC_METHOD1                     1314
#define IDC_METHOD2                     1315
#define IDC_METHOD3                     1316
#define IDC_TYPE1                       1317
#define IDC_TYPE2                       1318
#define IDC_TYPE3                       1319
#define IDC_TYPE4                       1320
#define IDC_TYPE5                       1321
#define IDC_TYPE6                       1322
#define IDC_WTYPE1                      1323
#define IDC_WTYPE2                      1324
#define IDC_WTYPE4                      1325
#define IDC_WTYPE7                      1326
#define IDC_DASTAT                      1327
#define IDC_STOREWOPP                   1328
#define IDC_INITCALC                    1329
#define IDC_KEEPOUTOPPS                 1330
#define IDC_XDIRECTFOILBAR              1331
#define IDC_REFFOIL                     1332
#define IDC_SHOW                        1333
#define IDC_MODFOIL                     1334
#define IDC_MIAREXWANABAR               1335
#define IDC_SPLINESTYLE                 1336
#define IDC_XDIRECTANABAR               1337
#define IDC_POLARBAR                    1338
#define IDC_PLRLIST                     1339
#define IDC_MIAREXW3DBAR                1340
#define IDC_AMAXSTAT                    1341
#define IDC_SCALEOPPBAR                 1342
#define IDC_ASTAT2                      1343
#define IDC_NEUTRALCHECK                1344
#define IDC_AFOILBAR                    1345
#define IDC_SCALE                       1346
#define IDC_FINVCTRLBAR                 1347
#define IDC_MAINGRID2                   1348
#define IDC_FOILSEL                     1349
#define IDC_XINVERSEBAR                 1350
#define IDC_XMINORGRID                  1351
#define IDC_MINORGRID2                  1352
#define IDC_YMINORGRID                  1353
#define IDC_SPECAL                      1355
#define IDC_SPECCL                      1356
#define IDC_FOILLIST                    1357
#define IDC_QRESET                      1359
#define IDC_LABELFONT                   1360
#define IDC_EXEC                        1361
#define IDC_PANELLIST                   1362
#define IDC_FILTER                      1363
#define IDC_GRAPHBORDER                 1364
#define IDC_CPXX                        1365
#define IDC_SPECIF                      1366
#define IDC_APPLY                       1367
#define IDC_XMINORUNIT                  1368
#define IDC_SKIP                        1369
#define IDC_OVERWRITE                   1370
#define IDC_DEFAULTS                    1371
#define IDC_RESTORE                     1372
#define IDC_LENGTH1                     1373
#define IDC_LENGTH2                     1374
#define IDC_LENGTH3                     1375
#define IDC_AREA                        1376
#define IDC_VOLUMEUNIT                  1377
#define IDC_LENGTH5                     1378
#define IDC_WEIGHTUNIT                  1379
#define IDC_SPEEDUNIT                   1380
#define IDC_LENGTH8                     1380
#define IDC_LENGTHUNIT                  1381
#define IDC_UNIT1                       1382
#define IDC_UNIT2                       1383
#define IDC_WLUNIT                      1384
#define IDC_LENGTHUNIT2                 1385
#define IDC_YMINORUNIT                  1386
#define IDC_MINORUNIT2                  1387
#define IDC_TWIST                       1395
#define IDC_SPECINV                     1396
#define IDC_FILTERPARAM                 1398
#define IDC_AUTONAME                    1399
#define IDC_SIDE1                       1400
#define IDC_GROUNDEFFECT                1401
#define IDC_SIDE2                       1402
#define IDC_DENSITY                     1403
#define IDC_VISCOSITY                   1404
#define IDC_SVISCOSITY                  1405
#define IDC_CNR                         1406
#define IDC_HEIGHT                      1407
#define IDC_CNI                         1408
#define IDC_POINTLIST                   1410
#define IDC_VARIABLETYPE                1411
#define IDC_REROOT                      1412
#define IDC_QINFSTAT                    1413
#define IDC_WVAR                        1414
#define IDC_CANCEL                      1416
#define IDC_RHO                         1417
#define IDC_NU                          1418
#define IDC_WINGSEL                     1419
#define IDC_VLMMESH                     1428
#define IDC_RADIO1                      1430
#define IDC_RADIO2                      1431
#define IDC_RADIO3                      1432
#define IDC_RADIO4                      1433
#define IDC_3DSURFACES                  1434
#define IDC_RADIO5                      1435
#define IDC_RADIO6                      1436
#define IDC_3DFRONT                     1437
#define IDC_3DLEFT                      1438
#define IDC_3DTOP                       1439
#define IDC_3DISO                       1440
#define IDC_3DRESET                     1441
#define IDC_NEWSPAN                     1442
#define IDC_3DOUTLINE                   1445
#define IDC_3DAXES                      1446
#define IDC_STDSETTINGS                 1447
#define IDC_3DLIGHT                     1448
#define IDC_3DPANELS                    1449
#define IDC_SHOWLIFT                    1450
#define IDC_WINDOWBK                    1451
#define IDC_SHOWICD                     1452
#define IDC_GAP                         1453
#define IDC_SHOWVCD                     1454
#define IDC_BLEND                       1455
#define IDC_LE                          1456
#define IDC_CNLIST                      1457
#define IDC_LIST                        1459
#define IDC_LBFOIL                      1460
#define IDC_XBODY                       1461
#define IDC_LEFT                        1462
#define IDC_XLESTAB                     1463
#define IDC_MIN                         1464
#define IDC_XLEWING2                    1465
#define IDC_CORESIZE                    1466
#define IDC_XLEWING                     1467
#define IDC_RIGHT                       1468
#define IDC_MAX                         1469
#define IDC_NXWAKEPANELS                1470
#define IDC_TOP                         1471
#define IDC_BOTTOM                      1472
#define IDC_SPANSCALE                   1473
#define IDC_ZLEFIN                      1474
#define IDC_SWEEPSCALE                  1475
#define IDC_TWISTSCALE                  1476
#define IDC_CREATELIST                  1477
#define IDC_FROMZERO                    1479
#define IDC_SPANFACTOR                  1480
#define IDC_ZLESTAB                     1481
#define IDC_PAPERSIZE                   1482
#define IDC_ZLEWING2                    1483
#define IDC_CHORDFACTOR                 1484
#define IDC_ZLEWING                     1485
#define IDC_GRAPHPREFS                  1486
#define IDC_ZBODY                       1486
#define IDC_YFACTOR                     1487
#define IDC_NEUTRAL                     1488
#define IDC_YTRANS                      1488
#define IDC_FIN                         1489
#define IDC_STAB                        1490
#define IDC_BIPLANE                     1491
#define IDC_STABLEVERARM                1492
#define IDC_STABSURFACE                 1493
#define IDC_STABVOLUME                  1497
#define IDC_FINSURFACE                  1498
#define IDC_STABTILT                    1499
#define IDC_PLANENAME                   1500
#define IDC_WINGTILT                    1503
#define IDC_WINGSPAN                    1504
#define IDC_WINGSURFACE                 1505
#define IDC_SURF1                       1506
#define IDC_SURF2                       1507
#define IDC_SAVEWOPPS                   1508
#define IDC_SURF4                       1509
#define IDC_SURF3                       1510
#define IDC_SAVEOPPS                    1511
#define IDC_SURF5                       1512
#define IDC_LEN1                        1513
#define IDC_LEN2                        1514
#define IDC_VLMTOTALPANELS              1515
#define IDC_WINGTILT2                   1516
#define IDC_LEN3                        1517
#define IDC_VLM1                        1518
#define IDC_LEN4                        1519
#define IDC_VLM2                        1520
#define IDC_LEN5                        1521
#define IDC_IMPORTWING                  1522
#define IDC_WAKEROLLUP                  1523
#define IDC_LEN6                        1524
#define IDC_SYMFIN                      1525
#define IDC_TILTEDGEOM                  1526
#define IDC_LENGTH                      1527
#define IDC_EXPORTWING                  1528
#define IDC_SLENGTH                     1529
#define IDC_LEN7                        1530
#define IDC_LENGTH6                     1531
#define IDC_FINTILT                     1532
#define IDC_LENGTH7                     1533
#define IDC_SURF6                       1536
#define IDC_IMPORTWING2                 1537
#define IDC_EXPORTWING2                 1538
#define IDC_SURF7                       1539
#define IDC_RESETWAKE                   1540
#define IDC_LEN8                        1541
#define IDC_LEN9                        1542
#define IDC_BODY                        1543
#define IDC_LEN10                       1544
#define IDC_SSURFACE                    1545
#define IDC_LEN12                       1546
#define IDC_LEN11                       1547
#define IDC_FORCE                       1548
#define IDC_LEN13                       1549
#define IDC_SSPEED                      1550
#define IDC_SWEIGHT                     1551
#define IDC_SMOMENT                     1552
#define IDC_GRAPHBK                     1553
#define IDC_HALFWING                    1554
#define IDC_PENWIDTH                    1555
#define IDC_YLEFIN                      1556
#define IDC_DIGITS                      1557
#define IDC_XLEFIN                      1558
#define IDC_PRINTERNAME                 1559
#define IDC_SWEEP                       1560
#define IDC_NEWCHORD                    1561
#define IDC_CHORDSCALE                  1562
#define IDC_MESSAGE                     1563
#define IDC_PANELS                      1564
#define IDC_WINGOUTLINE                 1565
#define IDC_DOUBLEFIN                   1566
#define IDC_DEFINEFIN                   1567
#define IDC_3DAXIS                      1568
#define IDC_DEFINEWING                  1569
#define IDC_DEFINEWING2                 1570
#define IDC_TANGENTSPLINE               1571
#define IDC_SDENSITY                    1572
#define IDC_PEDIT                       1574
#define IDC_IPEDIT                      1575
#define IDC_SFORCE                      1576
#define IDC_MOMENT                      1577
#define ID_BODYUPDATETIMER              1580
#define ID_THREADTIMER                  1581
#define IDC_NEUTRALLINE                 1590
#define IDC_XMAINGRID                   1591
#define IDC_CLR1                        5001
#define IDC_CLR2                        5002
#define IDC_CLR3                        5003
#define IDC_CLR4                        5004
#define IDC_CLR5                        5005
#define IDC_CLR6                        5006
#define IDC_CLR7                        5007
#define IDC_CLR8                        5008
#define IDC_CLR9                        5009
#define IDC_CLR10                       5010
#define IDC_CLR11                       5011
#define IDC_CLR12                       5012
#define IDC_CLR13                       5013
#define IDC_CLR14                       5014
#define IDC_CLR15                       5015
#define IDC_CLR16                       5016
#define IDC_CLR17                       5017
#define IDC_CLR18                       5018
#define IDC_CLR19                       5019
#define IDC_CLR20                       5020
#define IDC_CLR21                       5021
#define IDC_CLR22                       5022
#define IDC_CLR23                       5023
#define IDC_CLR24                       5024
#define IDC_CLR25                       5025
#define IDC_CLR26                       5026
#define IDC_CLR27                       5027
#define IDC_CLR28                       5028
#define IDC_CLR29                       5029
#define IDC_CLR30                       5030
#define IDC_CLR31                       5031
#define IDC_CLR32                       5032
#define IDC_CLR33                       5033
#define IDC_CLR34                       5034
#define IDC_CLR35                       5035
#define IDC_CLR36                       5036
#define IDC_OTHERCLR                    5040
#define IDD_CONTROLANALYSIS             5114
#define IDD_LLTDLG                      5115
#define IDD_LISTPLRDLG                  5116
#define IDD_3DCOLORDLG                  5117
#define IDD_WOPERDLGBAR                 5119
#define IDD_VLMDLG                      5120
#define IDD_W3DBAR                      5121
#define IDD_LEDLG                       5122
#define IDD_EDITFOILDLG                 5123
#define IDD_RELISTDLG                   5124
#define IDD_ABOUTBOX                    5125
#define IDD_BODYCTRLBAR                 5127
#define IDD_BODYSCALEDLG                5128
#define IDD_BGRIDDLG                    5129
#define ID_INDPROJECT                   5130
#define IDD_BODYTRANSDLG                5131
#define IDC_LOGFILE                     5137
#define IDC_SAVEASNEW                   5138
#define IDC_ITERGRAPH                   5139
#define IDC_ZOFFSET                     5140
#define IDC_NX                          5141
#define IDC_XFACTOR                     5142
#define IDC_AMBIENT                     5143
#define IDC_DELTAL                      5144
#define IDC_MATAMBIENT                  5145
#define IDC_XTRANS                      5146
#define IDC_XOFFSET                     5147
#define IDC_RED                         5148
#define IDC_DIFFUSE                     5149
#define IDC_MATDIFFUSE                  5150
#define IDC_GREEN                       5151
#define IDC_SPECULAR                    5152
#define IDC_MATSPECULAR                 5153
#define IDC_MATSHININESS                5154
#define IDC_XLIGHT                      5155
#define IDC_YLIGHT                      5156
#define IDC_ZLIGHT                      5157
#define IDC_CULLFACES                   5158
#define IDC_SHADE                       5159
#define IDC_NOTE                        5160
#define IDC_LOCALVIEW                   5161
#define IDC_DEPTHTEST                   5162
#define IDC_COLORMATERIAL               5163
#define IDC_BLUE                        5164
#define IDC_RELIST2                     5165
#define IDC_UFOLIST                     5166
#define IDC_DUPLICATE                   5167
#define IDC_COORDLIST                   5168
#define IDC_PROGRESS                    5169
#define IDC_CONTROLLIST                 5170
#define IDC_MATEMISSION                 5171
#define IDC_NFLAPS                      5174
#define IDC_SHOWCPSCALE                 5175
#define IDC_SHOWMOMENTS                 5176
#define IDC_WAKEPARAMS                  5179
#define IDC_SPANSLIDE                   5182
#define IDC_SPANPOS                     5183
#define IDC_WAKEDISPLAY                 5185
#define IDC_KEEPCURVE                   5187
#define IDC_RESETCURVES                 5188
#define IDC_FRAMEPOINTS                 5189
#define IDC_FRAMELIST                   5190
#define IDC_BODYCOLOR                   5191
#define IDC_BODYLIST                    5192
#define IDC_ZFACTOR                     5193
#define IDC_ZTRANS                      5194
#define IDC_DEFINESTAB                  5201
#define IDC_XDEGREE                     5204
#define IDC_HOOPDEGREE                  5205
#define IDC_NHPANELS                    5206
#define IDC_UNIT                        5207
#define IDC_MINORUNIT                   5208
#define IDC_MINSTYLE                    5209
#define IDC_GRIDSTYLE                   5210
#define IDC_MINORGRID                   5211
#define IDC_MAINGRID                    5212
#define IDC_LENGTH4                     5213
#define IDC_CLIPPLANEPOS                5214
#define IDC_FRAMEID                     5218
#define IDC_HOOPRESOLUTION              5219
#define IDC_XINTERVAL                   5220
#define IDC_SURFVELOCITIES              5221
#define IDC_TRANSITIONS                 5222
#define IDC_TOTAL3DPANELS               5223
#define IDC_LOCKED                      5224
#define IDC_AREA1                       5225
#define IDC_AREA2                       5226
#define IDC_PICKCENTER                  5227
#define IDC_WTYPE5                      5234
#define IDC_WTYPE6                      5235
#define IDC_NEWFOILNAME                 5237
#define IDC_BUTTON1                     5240
#define IDM_LOADREFFOIL                 32772
#define ID_EDIT_NEW                     32773
#define IDM_DEFINEWING                  32777
#define IDM_WANALYSIS                   32779
#define IDM_XFLR5                       32780
#define IDM_MIAREX                      32781
#define IDM_PRINT                       32783
#define IDM_XFLR5_POLARS                32785
#define IDM_BSPLINES                    32787
#define IDM_SPLINEDPOINTS               32789
#define IDM_FULLINVERSE                 32790
#define IDM_MIXEDINVERSE                32792
#define IDM_EXPORTWING                  32793
#define IDM_LOADWPLRS                   32794
#define IDC_CBFOIL                      32795
#define IDC_CBPLR                       32796
#define IDC_CBOPP                       32797
#define IDM_IMPORTWING                  32798
#define IDM_SAVEWPLRS                   32800
#define IDM_DELETEWPOLAR                32802
#define IDM_XFLR5_OPER                  32803
#define IDM_EDWING                      32804
#define IDM_FOILSTYLE                   32805
#define IDM_RENAMEWPOLAR                32806
#define IDM_AFOIL_GRID                  32807
#define IDM_XFLR5_EXPORTOPPOINTS        32808
#define IDM_AFOIL_PRINT                 32809
#define IDT_SHOWBL                      32810
#define IDM_DELETEWING                  32812
#define IDM_RENAMEWING                  32813
#define IDT_SHOWPRESSURE                32814
#define IDM_RESETDEF                    32815
#define IDM_RESETSCALES                 32816
#define IDM_WPOLAREXPORT                32818
#define IDM_AFOIL_EXPORTSPLINES         32824
#define IDM_LISTPLRS                    32825
#define IDM_SHOWPOLAR                   32826
#define IDM_DEFINEVAR                   32827
#define IDM_AFOIL_SFLOAD                32829
#define IDC_CBWING                      32830
#define IDM_AFOIL_SFSAVE                32832
#define IDC_CBWPLR                      32833
#define IDT_ZOOMLESS                    32835
#define IDC_CBWOPP                      32836
#define IDM_SINGLEGRAPH                 32837
#define IDM_TWOGRAPHS                   32838
#define IDM_PREFS                       32839
#define IDM_INDUCEDANGLE                32840
#define IDM_LIFT                        32841
#define IDM_AFOIL_NEWSPLINES            32843
#define IDM_PROFILEDRAG                 32844
#define IDM_REYNOLDS                    32845
#define IDM_CHANGENAME                  32847
#define IDM_DELWOPP                     32848
#define IDM_DELCURWOPP                  32849
#define IDM_WOPP                        32850
#define IDM_TOTALANGLE                  32851
#define IDM_LOGFILE                     32852
#define IDM_LOCALLIFT                   32853
#define IDM_TOPTRANS                    32855
#define IDM_BOTTRANS                    32856
#define IDM_DUPLICATEWING               32857
#define IDM_KEEPCURVE                   32859
#define IDM_RESETCURVES                 32860
#define IDM_POLARFILTER                 32861
#define IDM_DEFAULTS                    32862
#define IDM_CLRSETTINGS                 32863
#define IDM_SHOWPANELS                  32864
#define IDM_XFLR5_RESTOREDEF            32865
#define IDM_XFLR5_READDEF               32866
#define IDM_XFLR5_SAVEDEF               32867
#define IDM_XFLR5_ADVSETTINGS           32868
#define IDM_XFLR5_PANEL                 32869
#define IDM_XFLR5_CADD                  32870
#define IDM_EXPORTFOIL                  32871
#define IDM_RENAMEFOIL                  32872
#define IDM_REMOVEFOIL                  32873
#define IDM_XFLR5_LOGFILE               32874
#define IDM_ALLFOUR                     32876
#define IDM_XFLR5_CLCD                  32877
#define IDM_XFLR5_CLALPHA               32878
#define IDM_XFLR5_CLXTR                 32879
#define IDM_XFLR5_CMALPHA               32880
#define IDM_XFLR5_USERGRAPH             32881
#define IDM_CPI                         32882
#define IDM_XFLR5_DELETEPLR             32884
#define IDM_XFLR5_RENAMEPLR             32885
#define IDM_XFLR5_DELETEOPP             32886
#define IDM_XFLR5_EXPORTPLR             32887
#define IDM_XFLR5_GRAPHDLG              32889
#define IDM_GRAPHDLG                    32890
#define IDM_DEFINEGRAPH                 32891
#define IDM_XFLR5_COUPLEGRAPH           32893
#define IDM_RESTOREVARIABLES            32894
#define IDM_DELFOILPOLARS               32895
#define IDM_XFLR5_POLARFILTER           32896
#define IDM_XFLR5_RESTDEFGRAPHS         32898
#define IDM_XFLR5_RESETCURVES           32899
#define IDM_XFLR5_KEEPVISCOUS           32900
#define IDM_XFLR5_KEEPINVSICID          32901
#define IDM_TOOLBARS                    32902
#define IDM_RESETVIEW                   32905
#define IDM_DELETEPOINT                 32906
#define IDM_ADDPOINT                    32907
#define IDM_XFLR5_SHOWUSERGRAPH         32908
#define IDM_RESETQGRAPH                 32908
#define IDM_XFLR5_GRAPHOPTIONS          32910
#define IDM_RESETGRAPH                  32911
#define IDM_XFLR5_CPGRAPH               32912
#define IDM_XFLR5_QGRAPH                32913
#define IDM_XFLR5_GEOM                  32914
#define IDM_XFLR5_INTER                 32915
#define IDM_RESETSCALE                  32917
#define IDM_XFLR5_SINGLEANALYSIS        32918
#define IDM_XFLR5_BATCHANALYSIS         32919
#define IDT_LOAD                        32920
#define IDM_EXPORTTOAPP                 32924
#define IDT_PRINT                       32925
#define IDM_COLORSTYLES                 32926
#define IDM_EXPORTREFFOIL               32927
#define IDM_DELETESPOINT                32928
#define IDM_INSERTSPOINT                32929
#define IDM_INVERSERESTORE              32930
#define IDM_SHOWQPOINTS                 32931
#define IDM_STOREFOIL                   32932
#define IDC_STOREFOIL                   32935
#define IDM_SHOWREF                     32937
#define IDM_SHOWMOD                     32938
#define IDT_ZOOMIN                      32940
#define IDM_AFOIL_LOAD                  32941
#define IDT_ZOOMOUT                     32943
#define IDT_UNDO                        32944
#define IDT_REDO                        32945
#define IDM_GRAPHOPTIONS                32946
#define IDM_QINIT                       32947
#define IDM_QMOD                        32948
#define IDM_QVISC                       32949
#define ID_APP_OPEN                     32951
#define IDM_LOAD                        32952
#define IDM_INITXFOIL2                  32955
#define IDM_DELETEWPOLARS               32958
#define IDM_DELETEWOPPS                 32959
#define IDM_FOURGRAPHS                  32960
#define IDM_PREFERENCES                 32962
#define IDM_EXPORTWOPP                  32963
#define IDM_SELECTFOIL                  32964
#define IDM_DELETEINPUT                 32966
#define IDM_ADJUSTTOWING                32967
#define IDC_WOPP                        32968
#define IDC_WPOLARS                     32970
#define IDT_WOPP                        32971
#define IDT_WPOLARS                     32972
#define IDT_POLARS                      32973
#define IDT_OPPS                        32974
#define IDM_SETFOILPARAMS               32975
#define IDM_WRESET                      32976
#define IDM_PRESET                      32977
#define IDM_WPOLARRESET                 32979
#define IDM_IMPORTXFOILPOLAR            32980
#define IDM_UNITS                       32981
#define IDM_MIAREXSAVEAS                32982
#define IDM_NEWPROJECT                  32983
#define IDM_EDITWPLR                    32984
#define IDM_EDITPLR                     32985
#define IDM_DUPLICATEFOIL               32986
#define IDM_SAVE                        32987
#define IDM_SHOWXCP                     32991
#define IDM_INSERTPROJECT               32992
#define IDM_LOADPROJECT                 32993
#define IDM_SAVEPROJECT                 32994
#define IDM_SAVEPROJECTAS               32995
#define IDM_NORMALIZE                   32996
#define IDM_HIDEPOLARS                  32997
#define IDM_SHOWPOLARS                  32998
#define IDM_ROTATEFOIL                  32999
#define IDM_WGRAPHVAR                   33002
#define IDM_FOURWINGGRAPHS              33004
#define IDM_TWOWINGGRAPHS               33006
#define IDM_SHOWCURWOPP                 33007
#define IDM_SHOWALLWOPPS                33009
#define IDM_HIDEALLWOPPS                33010
#define IDM_DELALLPLRWOPPS              33011
#define IDM_LOADFILE                    33013
#define IDM_ADVSETTINGS                 33014
#define IDM_CHANGEREF                   33015
#define IDM_SHOWXCMREF                  33016
#define IDM_HIDEALLWPLRS                33017
#define IDM_SHOWALLWPLRS                33018
#define IDM_WNGHIDEALL                  33019
#define IDM_WNGSHOWALL                  33020
#define IDM_SHOWELLIPTIC                33021
#define IDM_CPGRAPHDLG                  33022
#define IDM_RESETWINGSCALE              33023
#define IDM_HIDEALLPOLARS               33024
#define IDM_SHOWALLPOLARS               33025
#define IDM_HIDEALLFOILS                33026
#define IDM_SHOWALLFOILS                33027
#define IDM_SAVEPLRFILE                 33028
#define IDM_DELETEFOIL                  33029
#define IDM_HIDEFOIL                    33030
#define IDM_SHOWFOIL                    33031
#define IDM_DEFINEPLANE                 33033
#define IDM_3DVIEW                      33034
#define IDM_ZOOMGRAPH                   33035
#define IDM_SCALEWING                   33037
#define IDM_RESET3DVIEW                 33038
#define IDM_CLOSEPROJECT                33040
#define IDM_RESETFOIL                   33042
#define IDM_RESETLEGEND                 33044
#define IDM_RESETWLEGEND                33045
#define IDM_RESETWINGLEGEND             33046
#define IDM_RESETYSCALE                 33047
#define IDT_ZOOMYONLY                   33048
#define IDM_TEGAP                       33049
#define IDM_LERAD                       33050
#define IDM_GEOM                        33051
#define IDM_PANEL                       33052
#define IDM_CADD                        33053
#define IDM_INTERPOLATE                 33054
#define IDM_EDITCOORD                   33056
#define IDM_SETFLAP                     33057
#define IDM_RESETALLSCALES              33058
#define IDM_APPEND                      33059
#define IDM_3DCLLEGEND                  33060
#define IDM_HIDEWOPPS                   33061
#define IDM_SHOWWOPPS                   33062
#define IDM_DELALLWOPPS                 33064
#define IDM_HIDEWINGOPPS                33065
#define IDM_SHOWWINGOPPS                33066
#define IDM_DELCUROPP                   33067
#define IDM_EXPORTCUROPP                33068
#define IDM_GUIDELINES                  33069
#define IDM_NACAFOILS                   33070
#define IDM_HPLOT                       33071
#define IDM_DTPLOT                      33072
#define IDM_DBPLOT                      33073
#define IDM_UEPLOT                      33074
#define IDM_CFPLOT                      33075
#define IDM_CDPLOT                      33076
#define IDM_NPLOT                       33077
#define IDM_CTPLOT                      33078
#define IDM_RTPLOT                      33079
#define IDM_RTLPLOT                     33080
#define IDM_LECIRCLE                    33082
#define IDM_SAVEOPTIONS                 33127
#define IDM_SINGLEGRAPH1                33153
#define IDM_SINGLEGRAPH2                33154
#define IDM_SINGLEGRAPH3                33155
#define IDM_SINGLEGRAPH4                33156
#define IDM_CPLEGEND                    33162
#define IDM_SAVEWING                    33165
#define IDM_SHOWSTAB                    33169
#define IDM_SHOWFIN                     33170
#define IDM_PLANEPREFS                  33172
#define IDM_AUTOWINGSCALES              33174
#define IDM_DELETEALL                   33175
#define IDM_WINGGRAPH1                  33176
#define IDM_WINGGRAPH2                  33177
#define IDM_WINGGRAPH3                  33178
#define IDM_WINGGRAPH4                  33179
#define IDT_NEWPROJECT                  33180
#define IDM_GLLIGHT                     33184
#define IDM_STREAMOPTIONS               33186
#define ID_IMPORTPOLAR_XFOILPOLAR       33187
#define ID_IMPORTPOLAR_JAVAFOILPOLAR    33188
#define IDM_SHOWCUROPP                  33189
#define IDM_SHOWOPPS                    33190
#define IDM_HIDEOPPS                    33191
#define IDM_SHOWFOILOPPS                33192
#define IDM_HIDEFOILOPPS                33193
#define IDM_SPLINECONTROLS              33195
#define IDM_SHOWLEGEND                  33197
#define IDM_MANAGEWINGS                 33200
#define ID_CURRENTFOIL_MANAGEFOILS      33201
#define IDM_INSERTBEFORE                33204
#define IDM_FOILDIRECTDESIGN            33215
#define IDM_SHOWCPGRAPH                 33234
#define IDM_EXPORTVLMPANELS             33251
#define IDM_SHOWWING2                   33253
#define IDM_RECENTFILE3                 33257
#define IDM_RECENTFILE1                 33261
#define IDM_RECENTFILE2                 33262
#define IDM_EDITCTRLPOINTS              33263
#define IDM_RECENTFILE5                 33266
#define IDM_RECENTFILE6                 33267
#define IDM_RECENTFILE7                 33268
#define IDM_RECENTFILE8                 33269
#define IDM_RECENTFILE4                 33270
#define IDM_CPVIEW                      33272
#define IDM_WADVSETTINGS                33274
#define IDM_INSERTPOINT                 33278
#define IDM_INSERTFRAME                 33279
#define IDM_DELETEFRAME                 33280
#define IDM_BODYDESIGN                  33282
#define IDM_DELETECURBODY               33292
#define IDM_RENAMECURBODY               33293
#define IDM_DUPLICATECURBODY            33294
#define IDM_SCALECURBODY                33295
#define IDM_EXPORTCURBODY               33296
#define IDM_SAVECURBODYASPROJECT        33297
#define IDM_NEWBODY                     33298
#define IDM_RESETFRAMESCALE             33302
#define IDM_RESETBODYSCALE              33303
#define IDM_BODYGRIDOPTIONS             33306
#define IDM_SHOWREFLECTED               33308
#define IDM_BODYRESOLUTION              33312
#define IDM_SHOWONLYACTIVEFRAME         33317
#define IDM_EXPORTCURRESULTS            33319
#define IDM_CONTROLPOLAR                33321
#define IDM_3DCOLORPREFS                33322
#define IDM_SELECTBODYOVERLAY           33328
#define IDM_OVERLAYSECTION              33330
#define IDM_IMPORTBODYDEFINITION        33333
#define IDM_EXPORTBODYDEFINITION        33334
#define IDM_TRANSLATECURBODY            33338
#define IDM_SAVEIMAGE                   33343
#define IDM_EXPORTGRAPHTOFILE           33348
#define ID_APP_EXIT2                    57666
#define ID_VIEW_STATUS_BAR2             59394

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        367
#define _APS_NEXT_COMMAND_VALUE         33350
#define _APS_NEXT_CONTROL_VALUE         5241
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
